let
    Fonte = Excel.Workbook(File.Contents("W:\CICLO\1_BASES\Bases_D-1\TarefasFechadasOntem_.xlsx"), null, true),
    TarefasFechadasOntem_Sheet = Fonte{[Item="TarefasFechadasOntem",Kind="Sheet"]}[Data],
    #"Cabeçalhos promovidos" = Table.PromoteHeaders(TarefasFechadasOntem_Sheet),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos",{{"NRBA", Int64.Type}, {"ESTADO", type text}, {"INICIOAGENDAMENTO", type datetime}, {"FIMAGENDAMENTO", type datetime}, {"DATALIMITEAGENDAMENTOMANUAL", type any}, {"ODC", Int64.Type}, {"APRAZADO", Int64.Type}, {"AREA", type text}, {"AREATECNICA", type text}, {"AREATRABALHO", type text}, {"ATIVIDADE", type text}, {"BLOQUEADO", Int64.Type}, {"CABO", type text}, {"CAIXA", type text}, {"CODENCERRAMENTO", type text}, {"CPF", Int64.Type}, {"CONTATO1", type text}, {"CONTATO2", type text}, {"CONTATO3", type text}, {"CONTATOEFETIVO", type text}, {"DATAABERTURAOS", type datetime}, {"DATAABERTURABA", type datetime}, {"DATAPROMESSA", type any}, {"DATAINDICADOR", type datetime}, {"INICIOEXECUCAO", type any}, {"FIMEXECUCAO", type datetime}, {"DURACAO", Int64.Type}, {"EMPRESA", type text}, {"ERROINTEGRACAO", type text}, {"ESTACAO", type text}, {"FILAPOSTO", type text}, {"GERENCIA", type text}, {"IDDADOSREDE", type text}, {"INSTALACAOUNICA", Int64.Type}, {"VENDACONJUNTA", Int64.Type}, {"INSTUNICAREALIZADA", Int64.Type}, {"LATITUDE", Int64.Type}, {"LOCALIDADE", type any}, {"LOCALIDADEREMOTA", Int64.Type}, {"LONGITUDE", Int64.Type}, {"MACROATIVIDADE", type text}, {"MOTIVOREPARO", type any}, {"NOMECLIENTE", type text}, {"CIRCUITO", type text}, {"DOCUMENTOASSOCIADO", type text}, {"NUMEROFISICO", Int64.Type}, {"OBSERVACOES", type text}, {"OPERADORAGENDAMENTO", type text}, {"PORTABILIDADE", Int64.Type}, {"POSSUIVELOX", Int64.Type}, {"PRIORIDADE", Int64.Type}, {"PRIORIDADE OP.", type text}, {"PSUP", Int64.Type}, {"QTDDPONTOS", Int64.Type}, {"RECLAMACAO", type text}, {"REGIAO", type text}, {"REINCIDENCIA", Int64.Type}, {"REPAROGARANTIA", Int64.Type}, {"SISTEMAABERTURA", type text}, {"SKILLS", type text}, {"TECNICO", type text}, {"TELEFONEBUSCA", Int64.Type}, {"TERMINAL", type text}, {"BINAGEMEXECUTADA", Int64.Type}, {"SETOR", type text}, {"TIPOCLIENTE", type text}, {"UF", type text}, {"USARIOCIENTEUP", type any}, {"CODIGOROTEAMENTO", type text}, {"PRONTOPARAEXECUCAO", type text}, {"FLAGAGENDAMENTO", type text}, {"GRAM", type text}, {"GRA", type text}, {"MATRICULATECNICO", type text}, {"MERCADO", type text}, {"VELOCIDADECONTRATADA", type text}, {"TESTEFINAL", type text}, {"TIPODEENCERRAMENTO", type text}, {"SERVICO", type text}, {"TIPOTERMINAL", type text}, {"INICIODESLOCAMENTO", type datetime}, {"CONTRATO", Int64.Type}, {"ACESSOGPON", type text}, {"INDICADOR_TEC_AUX", Int64.Type}, {"PORTABILIDADE_RECEPTORA", Int64.Type}, {"PORTABILIDADE_INTERNA", Int64.Type}, {"PORT_INT_TROCA_TECNOLOGIA", Int64.Type}, {"NUMERO_PORTADO", Int64.Type}, {"IDBUNDLE", type text}}),
    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"NRBA", "ESTADO", "INICIOEXECUCAO", "FIMEXECUCAO", "DURACAO", "UF", "PRONTOPARAEXECUCAO", "MATRICULATECNICO"}),
    #"Personalização Adicionada1" = Table.AddColumn(#"Outras Colunas Removidas", "TEMPOEXECUCAO", each [FIMEXECUCAO]-[INICIOEXECUCAO]),
    #"Personalização Adicionada" = Table.AddColumn(#"Personalização Adicionada1", "BALONGO", each [DURACAO] + 1200),
    #"Horas Inseridas" = Table.AddColumn(#"Personalização Adicionada", "DurationHours", each Duration.Hours([TEMPOEXECUCAO]), type number),
    #"Minutos Inseridos" = Table.AddColumn(#"Horas Inseridas", "DurationMinutes", each Duration.Minutes([TEMPOEXECUCAO]), type number),
    #"Personalização Adicionada2" = Table.AddColumn(#"Minutos Inseridos", "TempoReal", each ([DurationHours]*60*60)+([DurationMinutes]*60)),
    #"Personalização Adicionada3" = Table.AddColumn(#"Personalização Adicionada2", "BALONGO_BIN", each if [TempoReal] >[BALONGO]  then 1 else 0),
    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada3", each ([ESTADO] <> "Cancelado")),
    #"Personalização Adicionada4" = Table.AddColumn(#"Linhas Filtradas", "Denominador", each 1),
    #"Linhas Agrupadas" = Table.Group(#"Personalização Adicionada4", {"ESTADO", "UF", "MATRICULATECNICO"}, {{"QtBALONGO", each List.Sum([BALONGO_BIN]), type number}, {"QTBATOTAIS", each List.Sum([Denominador]), type number}})
in
    #"Linhas Agrupadas"