let
    Fonte = Excel.Workbook(File.Contents("W:\CRM\CONFIGURACAO\1_BASES\apoio\CALENDARIOS\calendariounificado.xlsx"), null, true),
    Plan1_Sheet = Fonte{[Item="Plan1",Kind="Sheet"]}[Data],
    #"Cabeçalhos promovidos" = Table.PromoteHeaders(Plan1_Sheet),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos",{{"REGIONAL", type text}, {"MATRICULA", type text}, {"01--", type text}, {"02--", type text}, {"03--", type text}, {"04--", type text}, {"05--", type text}, {"06--", type text}, {"07--", type text}, {"08--", type text}, {"09--", type text}, {"10--", type text}, {"11--", type text}, {"12--", type text}, {"13--", type text}, {"14--", type text}, {"15--", type text}, {"16--", type text}, {"17--", type text}, {"18--", type text}, {"19--", type text}, {"20--", type text}, {"21--", type text}, {"22--", type text}, {"23--", type text}, {"24--", type text}, {"25--", type text}, {"26--", type text}, {"27--", type text}, {"28--", type text}, {"29--", type text}, {"30--", type text}, {"31--", type text}, {"OBS", type any}}),
    #"Outras Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Tipo Alterado", {"REGIONAL", "MATRICULA", "OBS"}, "Atributo", "Valor"),
    #"Remoção do Dia 31 **" = Table.SelectRows(#"Outras Colunas Não Dinâmicas", each ([Valor] <> "-") and ([Atributo] <> "31--")),
    #"Valor Substituído" = Table.ReplaceValue(#"Remoção do Dia 31 **","--","/04/2019",Replacer.ReplaceText,{"Atributo"}),
    #"Data Analisada" = Table.TransformColumns(#"Valor Substituído",{{"Atributo", each Date.From(DateTimeZone.From(_)), type date}}),
    #"Formata Data como Inteiro" = Table.TransformColumnTypes(#"Data Analisada",{{"Atributo", Int64.Type}}),
    #"Criando a Chave (TR & Atributo)" = Table.AddColumn(#"Formata Data como Inteiro", "Chave", each Text.From([Atributo])&[MATRICULA]),
    #"Mescla do Calendario & Fila de Solicitação" = Table.NestedJoin(#"Criando a Chave (TR & Atributo)",{"Chave"},fila_solicitacoes_,{"Chave"},"FS"),
    #"FS Expandido" = Table.ExpandTableColumn(#"Mescla do Calendario & Fila de Solicitação", "FS", {"TIPO", "DATA INICIO", "DATA FIM", "MOTIVO", "STATUS", "PeriodoIndisp"}, {"FS.TIPO", "FS.DATA INICIO", "FS.DATA FIM", "FS.MOTIVO", "FS.STATUS", "FS.PeriodoIndisp"}),
    #"Definição do Numerador" = Table.AddColumn(#"FS Expandido", "Numerador", each if [FS.MOTIVO] <> null and [Valor] = "Trabalha" then 1 else null),
    #"Definição do Denominador" = Table.AddColumn(#"Definição do Numerador", "Denominador", each if [Valor] = "Trabalha" then 1 else 0),
    #"Mescla do Calendario & Tecnico Click" = Table.NestedJoin(#"Definição do Denominador",{"MATRICULA"},TecnicosdoClick,{"MATRÍCULA"},"TC"),
    #"TC Expandido" = Table.ExpandTableColumn(#"Mescla do Calendario & Tecnico Click", "TC", {"NOMETÉCNICO", "UF", "GRAM", "GRA", "SETOR", "SUPERVISOR", "GERENTE", "PERFILTECNICO"}, {"TC.NOMETÉCNICO", "TC.UF", "TC.GRAM", "TC.GRA", "TC.SETOR", "TC.SUPERVISOR", "TC.GERENTE", "TC.PERFILTECNICO"}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"TC Expandido",{{"Atributo", type date}})
in
    #"Tipo Alterado1"